# Generated by Django 2.2.12 on 2020-04-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarydashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LibUser',
        ),
    ]
