# Generated by Django 2.2.12 on 2020-04-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarydashboard', '0002_auto_20200413_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibUser',
        ),
    ]
