# Generated by Django 2.2.12 on 2020-04-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarydashboard', '0006_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
