# Generated by Django 2.2.12 on 2020-04-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarydashboard', '0008_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libuser',
        ),
    ]
