# Generated by Django 2.2.12 on 2020-04-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarydashboard', '0009_delete_libuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.IntegerField()),
            ],
        ),
    ]
