# Generated by Django 2.2.12 on 2020-04-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarydashboard', '0010_libuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookIssueTo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='dateOfIssue',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='dateOfSubmit',
            field=models.DateTimeField(null=True),
        ),
    ]
