# Generated by Django 2.2.12 on 2020-04-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarydashboard', '0011_auto_20200414_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
