# Generated by Django 2.2.12 on 2020-04-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarydashboard', '0012_books_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('Review', models.CharField(max_length=500)),
            ],
        ),
    ]
